# Generated by Django 4.0.3 on 2024-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_auto_20180406_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='reservation_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
