# Generated by Django 4.0.3 on 2024-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0007_orders_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Official', 'Official'), ('Unofficial', 'Unofficial')], default='Official', max_length=10),
        ),
    ]
