# Generated by Django 4.0.3 on 2024-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0008_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cl',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='em',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='mob',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
