# Generated by Django 4.0.3 on 2024-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0004_vehicles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='reservation_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
