# Generated by Django 4.0.3 on 2024-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0005_vehicles_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='driver_contact',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
